name: Deploy Node App to AWS Lambda

on:
  push:
    branches:
      - main   # CHANGE if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Get latest repo code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 — Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Step 3 — Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4 — Create deployment zip
      - name: Create zip package
        run: |
          zip -r function.zip . \
          -x "*.git*" \
          -x "node_modules/aws-sdk/*"

      # Step 5 — Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 6 — Deploy to Lambda
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION }} \
            --zip-file fileb://function.zip